include(GNUInstallDirs)
include(CMakePackageConfigHelpers)

set(CLOC_INSTALL_CMAKEDIR "${CMAKE_INSTALL_LIBDIR}/cmake/Cloc")

install(TARGETS cloc_core
    EXPORT ClocTargets
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)

install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/include/
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)

install(DIRECTORY ${CLOC_GENERATED_INCLUDE_DIR}/
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)

configure_package_config_file(
    "${CMAKE_CURRENT_SOURCE_DIR}/cmake/ClocConfig.cmake.in"
    "${CMAKE_CURRENT_BINARY_DIR}/ClocConfig.cmake"
    INSTALL_DESTINATION "${CLOC_INSTALL_CMAKEDIR}"
)

write_basic_package_version_file(
    "${CMAKE_CURRENT_BINARY_DIR}/ClocConfigVersion.cmake"
    VERSION "${PROJECT_VERSION}"
    COMPATIBILITY SameMajorVersion
)

install(EXPORT ClocTargets
    NAMESPACE Cloc::
    DESTINATION ${CLOC_INSTALL_CMAKEDIR}
)

install(FILES
    "${CMAKE_CURRENT_BINARY_DIR}/ClocConfig.cmake"
    "${CMAKE_CURRENT_BINARY_DIR}/ClocConfigVersion.cmake"
    DESTINATION ${CLOC_INSTALL_CMAKEDIR}
)
